### PR TITLE
Add MATLAB Unit Tests and GitHub CI

### PR DESCRIPTION
**Pull request by singhbal-baljinder**
After the introduction of the package structure, the tests have been ported using the [Class-based Unit Test framework](https://it.mathworks.com/help/matlab/class-based-unit-tests.html) and are automatically run by a custom MATLAB CI.
This concludes https://github.com/robotology/urdf2casadi-matlab/issues/18.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
Great!

**Comment by traversaro** [comment]
(Probably you may want to merge with squash)

**Comment by traversaro** [comment]
I guess there are some steps that can be simplified, but for now I think it is more important to merge as it is, then we can simplify it later.

**Comment by singhbal-baljinder** [comment]
> I guess there are some steps that can be simplified, but for now I think it is more important to merge as it is, then we can simplify it later.

Probably yes, I mostly focused on the MATLAB related errors and incompatibilities in this PR. To make sure the tests were running.

**Pull request merged**
