### PR TITLE
Use package namespace

### LINKED ISSUE #17: Use MATLAB package namespace
Having a package namespace avoids name conflicts with other functions in the MATLAB path. See https://it.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html and https://github.com/robotology/urdf2casadi-matlab/issues/16#issuecomment-887344605.

### PR DESCRIPTION
**Pull request by singhbal-baljinder**
This PR modifies the structure by using MATLAB package and sub-package structure, see https://it.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html. 
This fixes #17.

### CODE REVIEW

**Comment by traversaro** [comment]
Not super-problematic, but it seems you did some commit with a wrong email or some email not registered in GitHub?

**Comment by traversaro** [comment]
Probably this section of the README needs to be changed: https://github.com/robotology/urdf2casadi-matlab#usage ?

**Comment by singhbal-baljinder** [comment]
> Probably this section of the README needs to be changed: https://github.com/robotology/urdf2casadi-matlab#usage ?

I have added a couple of lines referencing directly the MATLAB documentation on how to use packages. The rest should be the same, let me know if you want additional changes.

**Comment by traversaro** [comment]
> 
> 
> > Probably this section of the README needs to be changed: https://github.com/robotology/urdf2casadi-matlab#usage ?
> 
> I have added a couple of lines referencing directly the MATLAB documentation on how to use packages. The rest should be the same, let me know if you want additional changes.

Should we remove the "and all its subfolders" from the first sentence?

**Comment by singhbal-baljinder** [comment]
> > > Probably this section of the README needs to be changed: https://github.com/robotology/urdf2casadi-matlab#usage ?
> > 
> > 
> > I have added a couple of lines referencing directly the MATLAB documentation on how to use packages. The rest should be the same, let me know if you want additional changes.
> 
> Should we remove the "and all its subfolders" from the first sentence?

The package and sub-package members should not be added to the path, it is sufficient to add the parent directory of `+urdf2casadi/` (see https://it.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html#brfynt_-3). On the other hand, the scripts under the `urdf2casadi-matlab/Verification/testOnMatlab/` folder need the functions currently stored under the `urdf2casadi-matlab/Verification/auxiliaryVerificationFunctions` folder, so if we do not add them in the path one cannot run the tests.

**Comment by traversaro** [comment]
Ah, ok.

**Review by traversaro — APPROVED** [review]

**Pull request merged**
